
export const GET_PRODUCTS_DATA_REQUEST = "GET_PRODUCTS_DATA_REQUEST";

export const GET_PRODUCTS_DATA_SUCCESS = "GET_PRODUCTS_DATA_SUCCESS";

export const GET_PRODUCTS_DATA_FAILURE = "GET_PRODUCTS_DATA_FAILURE";








export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";

export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";

export const GET_SINGLE_PRODUCT_FAILURE = "GET_SINGLE_PRODUCT_FAILURE";
















export const ADD_PRODUCT_CART_REQUEST = "ADD_PRODUCT_CART_REQUEST";

export const ADD_PRODUCT_CART_SUCCESS = "ADD_PRODUCT_CART_SUCCESS";

export const ADD_PRODUCT_CART_FAILURE = "ADD_PRODUCT_CART_FAILURE";